{
 "title": "op-talos",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Block processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration of building a block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(reth_op_rbuilder_total_block_built_duration)",
     "legendFormat": "Block building job duration"
    }
   ]
  },
  {
   "title": "Block built success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_block_built_success",
     "legendFormat": "Block number"
    }
   ]
  },
  {
   "title": "Builder blocks built per second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(reth_op_rbuilder_block_built_success[$__rate_interval])",
     "legendFormat": "Block building rate"
    }
   ]
  },
  {
   "title": "Payload byte size heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_payload_byte_size",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Payload byte size",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_payload_byte_size",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  { "title": "Transaction processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Duration of payload simulation of all transactions heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_payload_tx_simulation_duration",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Duration of payload simulation of all transactions",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_payload_tx_simulation_duration",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Number of transaction considered for inclusion in the block heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_payload_num_tx_considered",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Number of transaction considered for inclusion in the block",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_payload_num_tx_considered",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Number of transactions in the payload that failed simulation heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_payload_num_tx_simulated_fail",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Number of transactions in the payload that failed simulation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_payload_num_tx_simulated_fail",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Duration of fetching transactions from the pool",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_transaction_pool_fetch_duration",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Number of reverted transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_num_reverted_tx",
     "legendFormat": "Reverted Transactions"
    }
   ]
  },
  {
   "title": "Number of transactions in the payload that were successfully simulated heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_payload_num_tx_simulated",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Number of transactions in the payload that were successfully simulated",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_payload_num_tx_simulated",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Byte size of transactions heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    { "expr": "reth_op_rbuilder_tx_byte_size", "legendFormat": "{{client_type}} q={{quantile}}" }
   ]
  },
  {
   "title": "Byte size of transactions",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    { "expr": "reth_op_rbuilder_tx_byte_size", "legendFormat": "{{client_type}} q={{quantile}}" }
   ]
  },
  {
   "title": "Gas used by the last processed block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_block_gas_used",
     "legendFormat": "Gas units"
    }
   ]
  },
  {
   "title": "Number of reverted transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_num_reverted_tx",
     "legendFormat": "Reverted tx number"
    }
   ]
  },
  { "title": "State processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Duration of sequencer transaction execution heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_sequencer_tx_duration",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Duration of sequencer transaction execution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_sequencer_tx_duration",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Duration of state root calculation heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_state_root_calculation_duration",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Duration of state root calculation",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_state_root_calculation_duration",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  { "title": "Assertion processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Total gas used by assertions in the last processed block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_block_assertion_gas_used",
     "legendFormat": "Gas used"
    }
   ]
  },
  {
   "title": "Number of invalidated transactions in a block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_num_invalidated_tx",
     "legendFormat": "Invalidatet Tx number"
    }
   ]
  },
  {
   "title": "Distribution of the number of assertions executed per block heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_assertions_executed_per_block",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Distribution of the number of assertions executed per block",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_assertions_executed_per_block",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Distribution of the number of assertions per transaction heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_assertions_per_tx",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  },
  {
   "title": "Distribution of the number of assertions per transaction",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "reth_op_rbuilder_assertions_per_tx",
     "legendFormat": "{{client_type}} q={{quantile}}"
    }
   ]
  }
 ]
}