{
 "title": "Bedrock Challenger",
 "description": "Monitoring for op-challenger instances",
 "tags": [ "public" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(op_challenger_up,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(op_challenger_up{cluster=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "op_challenger_info{cluster=${cluster:doublequote},namespace=${namespace:doublequote}}",
     "legendFormat": "Version: {{version}}"
    }
   ]
  },
  {
   "title": "Actions Performed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without (instance, pod) (op_challenger_moves{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Moves"
    },
    {
     "expr": "max without (instance, pod) (op_challenger_steps{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Steps"
    },
    {
     "expr": "max without (instance, pod) (op_challenger_cannon_execution_time_count{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Cannon Executions"
    }
   ]
  },
  {
   "title": "Sender ETH Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 9, "y": 2 },
   "targets": [
    {
     "expr": "op_challenger_balance{cluster=${cluster:doublequote},namespace=${namespace:doublequote}}",
     "legendFormat": "{{namespace}}/{{container}}"
    }
   ]
  },
  {
   "title": "Games",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance, pod) (op_challenger_tracked_games{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Large Preimages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without (instance, pod) (op_challenger_preimage_count{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Proposals"
    },
    {
     "expr": "max without (instance, pod) (op_challenger_preimage_challenge_failed{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Failed Challenges"
    },
    {
     "expr": "max without (instance, pod) (op_challenger_preimage_challenged{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Successful Challenges"
    }
   ]
  },
  { "title": "Executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "VM Execution Times",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(op_challenger_asterisc_execution_time_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}}[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Game Execution",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, status) (op_challenger_executors{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Executors {{status}}"
    },
    {
     "expr": "sum by (cluster, namespace) (op_challenger_inflight_games{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "In Flight"
    },
    {
     "expr": "max by (cluster, namespace, job) (op_challenger_highest_acted_l1_block{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Highest L1 Block"
    }
   ]
  },
  {
   "title": "Executor Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, pod) (op_challenger_executors{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, status=\"active\"}) / ignoring (status) (sum without (status, instance, pod) (op_challenger_executors{cluster=${cluster:doublequote},namespace=${namespace:doublequote}}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest L1 Block Processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cluster, namespace, job) (op_challenger_highest_acted_l1_block{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Highest processed L1 block {{namespace}}"
    }
   ]
  },
  { "title": "Timing Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Claim Resolution Times",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(op_challenger_claim_resolution_time_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}}[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Game Progression Times",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(op_challenger_game_act_time_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}}[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Contract Request Times",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(op_challenger_contracts_requests_duration_seconds_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}}[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Claim Resolution Time",
   "type": "timeseries",
   "description": "Time spent",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, op_challenger_claim_resolution_time_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, op_challenger_claim_resolution_time_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.75, op_challenger_claim_resolution_time_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, op_challenger_claim_resolution_time_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "0.50"
    }
   ]
  },
  {
   "title": "Game Progression Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, op_challenger_game_act_time_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, op_challenger_game_act_time_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.75, op_challenger_game_act_time_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, op_challenger_game_act_time_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "0.50"
    }
   ]
  },
  {
   "title": "Contract Time 0.99% By Method",
   "type": "timeseries",
   "description": "Time spent",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(op_challenger_contracts_requests_duration_seconds_bucket{cluster=${cluster:doublequote},namespace=${namespace:doublequote}}[10m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Process / Disk Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max without (instance, pod) (container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\", container=\"op-challenger\"})",
     "legendFormat": "container_memory_rss"
    },
    {
     "expr": "max without (instance, pod) (go_memstats_alloc_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=\"op-challenger\"})",
     "legendFormat": "go_memstats_alloc_bytes"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\", namespace=\"op-challenger\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", namespace=\"op-challenger\", resource=\"cpu\"}\n)\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", namespace=\"op-challenger\", resource=\"cpu\"}\n)\n",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Error and Warning Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "count_over_time ({cluster=\"$cluster\", namespace=\"$namespace\", app=\"op-challenger\"} | logfmt lvl | label_format level=lvl | level != \"\" | level != \"info\" [5m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Available Disk",
   "type": "timeseries",
   "description": "Bytes remaining in the PVC",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "min by (cluster, namespace) (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=\"op-challenger-data\"})",
     "legendFormat": "{{cluster}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Challenger Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", app=\"op-challenger\"} | logfmt | lvl = `error` | label_format level=lvl"
    }
   ]
  },
  {
   "title": "Challenger Warn Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", app=\"op-challenger\"} | logfmt | lvl = `warn` | label_format level=lvl"
    }
   ]
  },
  {
   "title": "Full Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", app=\"op-challenger\"} | logfmt | label_format level=lvl"
    }
   ]
  }
 ]
}