{
 "title": "Proposer",
 "tags": [ "public" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(op_node_default_up,cluster)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values({cluster=\"$cluster\", namespace=~\".*proposer\"},stack_optimism_io_network)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proposed Block Numbers",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "op_proposer_default_refs_number{cluster=\"$cluster\", layer=\"l2\", stack_optimism_io_network=\"$network\"}",
     "legendFormat": "l2_proposed_block_number"
    },
    {
     "expr": "op_proposer_default_refs_number{cluster=\"$cluster\", layer=\"l1_origin\", stack_optimism_io_network=\"$network\"}",
     "legendFormat": "l1_origin_proposed_number"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_pending_txs{cluster=\"$cluster\", stack_optimism_io_network=\"$network\"}",
     "legendFormat": "pending_txs"
    }
   ]
  },
  {
   "title": "Publishing Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_tx_publish_error_count{cluster=\"$cluster\", stack_optimism_io_network=\"$network\"}",
     "legendFormat": "publish_err_{{error}}_count"
    }
   ]
  },
  {
   "title": "Proposer Nonce",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_proposer_default_txmgr_current_nonce{cluster=\"$cluster\", stack_optimism_io_network=\"$network\"}",
     "legendFormat": "nonce"
    }
   ]
  },
  {
   "title": "Balance (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 7, "x": 3, "y": 16 },
   "targets": [
    {
     "expr": "op_proposer_default_balance{cluster=\"$cluster\", stack_optimism_io_network=\"$network\"}",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Balance (ETH)",
   "type": "stat",
   "description": "Current account balance in ETH",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(op_proposer_default_balance{cluster=\"$cluster\", stack_optimism_io_network=\"$network\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}