{
 "title": "Bedrock Networks",
 "tags": [ "public" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "network",
    "query": {
     "query": "label_values(op_node_default_up, stack_optimism_io_network)"
    }
   },
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "label_values(op_node_default_up{stack_optimism_io_network=\"$network\"},namespace)"
    }
   },
   {
    "name": "layer",
    "label": "Layer",
    "query": {
     "query": "label_values(op_node_default_refs_number{stack_optimism_io_network=\"$network\", namespace=~\"$node\"},layer)"
    }
   },
   {
    "name": "safety",
    "label": "Safety type",
    "query": {
     "query": "label_values(op_node_default_refs_number{stack_optimism_io_network=\"$network\", namespace=~\"$node\", layer=~\"$layer\"},type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rollup nodes - Block numbers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "op_node_default_refs_number{layer=\"l1\",type=\"l1_head\",namespace=~\"$node\",stack_optimism_io_network=${network:doublequote},layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   - L1 head"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l2\",type=\"l2_safe\",namespace=~\"$node\",stack_optimism_io_network=${network:doublequote},layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   - L2 safe"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l2\",type=\"l2_unsafe\",namespace=~\"$node\",stack_optimism_io_network=${network:doublequote},layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   - L2 unsafe"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l1_origin\",type=\"l2_safe\",namespace=~\"$node\",stack_optimism_io_network=${network:doublequote},layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}} - L1 origin of L2 safe"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l1_origin\",type=\"l2_unsafe\",namespace=~\"$node\",stack_optimism_io_network=${network:doublequote},layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}} - L1 origin of L2 unsafe"
    }
   ]
  },
  {
   "title": "Replica heights (geth)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "healthcheck_reference_height{stack_optimism_io_network=\"$network\", namespace=~\"$node\"}",
     "legendFormat": "{{namespace}} - reference"
    },
    {
     "expr": "healthcheck_last_matching_state_root_height{stack_optimism_io_network=\"$network\", namespace=~\"$node\"}",
     "legendFormat": "{{namespace}} - matching"
    },
    {
     "expr": "healthcheck_target_height{stack_optimism_io_network=\"$network\", namespace=~\"$node\"}",
     "legendFormat": "{{namespace}} - height"
    }
   ]
  },
  {
   "title": "Divergence",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "healthcheck_is_currently_diverged{stack_optimism_io_network=\"$network\", stack_optimism_io_deployment_type=\"replica\", namespace=~\"$node\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "TXs sequenced per second",
   "type": "timeseries",
   "description": "There is a current bug in the op-node metrics implementation that if the non-leader sequencers are behind the current tip and catching up, they will emit TX-Sequenced metrics, however they are not actually sequencing new TXs to the chain.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(op_node_default_transactions_sequenced_total{stack_optimism_io_network=\"$network\", stack_optimism_io_deployment_type=\"sequencer\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rollup nodes - Block latency (seen - timestamp)",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "-min_over_time(op_node_default_refs_latency{stack_optimism_io_network=${network:doublequote}, namespace=~\"$node\",layer=~\"$layer\",type=~\"$safety\"}[$__interval])",
     "legendFormat": "{{namespace}} {{type}}"
    }
   ]
  },
  {
   "title": "TXs sequenced",
   "type": "status-history",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by (namespace) (increase(op_node_default_transactions_sequenced_total{stack_optimism_io_network=\"$network\", stack_optimism_io_deployment_type=\"sequencer\"}[2m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Unsafe-block processing time / real time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 18, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(op_node_default_events_process_time{stack_optimism_io_network=${network:doublequote}, namespace=~\"$node\", deriver=\"engine\", event_type=\"process-unsafe-payload\"}[$__rate_interval])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rollup nodes - Block timestamp",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "last_over_time(op_node_default_refs_time{stack_optimism_io_network=${network:doublequote}, namespace=~\"$node\",layer=~\"$layer\",type=~\"$safety\"}[$__interval])",
     "legendFormat": "{{namespace}} {{type}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "op_node_default_p2p_peer_count{stack_optimism_io_network=${network:doublequote}, namespace=~\"$node\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rollup nodes - Block hashes",
   "type": "status-history",
   "gridPos": { "h": 39, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "op_node_default_refs_hash{layer=\"l1\", type=\"l1_head\", stack_optimism_io_network=\"$network\", namespace=~\"$node\",layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   -  L1 head"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l1\", type=\"l1_safe\", stack_optimism_io_network=\"$network\", namespace=~\"$node\",layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   -   L1 safe"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l1\", type=\"l1_finalized\", stack_optimism_io_network=\"$network\", namespace=~\"$node\",layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   -  L1 finalized"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l2\", type=\"l2_unsafe\", stack_optimism_io_network=\"$network\", namespace=~\"$node\",layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   -  L2 unsafe"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l2\", type=\"l2_safe\", stack_optimism_io_network=\"$network\", namespace=~\"$node\",layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   -  L2 safe"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l2\", type=\"l2_finalized\", stack_optimism_io_network=\"$network\", namespace=~\"$node\",layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   -  L2 finalized"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l1_origin\", type=\"l2_unsafe\", stack_optimism_io_network=\"$network\", namespace=~\"$node\",layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   -  L2 unsafe L1 origin"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l1_origin\", type=\"l2_safe\", stack_optimism_io_network=\"$network\", namespace=~\"$node\",layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   -  L2 safe L1 origin"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l1_origin\", type=\"l2_finalized\", stack_optimism_io_network=\"$network\", namespace=~\"$node\",layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   -  L2 finalized L1 origin"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l1\", type=\"l1_derived\", stack_optimism_io_network=\"$network\", namespace=~\"$node\",layer=~\"$layer\",type=~\"$safety\"}",
     "legendFormat": "{{namespace}}   -  L1 derived input"
    }
   ]
  }
 ]
}