{
 "title": "Bedrock Nodes",
 "tags": [ "public" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "query": {
     "query": "label_values(op_node_default_up, stack_optimism_io_network)"
    }
   },
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "label_values(op_node_default_up{stack_optimism_io_network=\"$network\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Node version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_info{stack_optimism_io_network=${network:doublequote},namespace=${node:doublequote}}",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "Required protocol version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_protocol_versions{stack_optimism_io_network=${network:doublequote},namespace=${node:doublequote}}",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "op-node supported protocol version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_protocol_versions{stack_optimism_io_network=${network:doublequote},namespace=${node:doublequote}}",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "Last Reorg",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "op_node_default_last_pipeline_reset_unix{namespace=${node:doublequote},stack_optimism_io_network=${network:doublequote}} * 1000"
    }
   ]
  },
  {
   "title": "Seconds per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "1/max(rate(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l1_head\", layer=\"l1\", stack_optimism_io_network=${network:doublequote}}[$__interval]))",
     "legendFormat": "L1"
    },
    {
     "expr": "1/max(rate(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_safe\", layer=\"l2\", stack_optimism_io_network=${network:doublequote}}[10m]))",
     "legendFormat": "Safe L2"
    },
    {
     "expr": "1/max(rate(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_unsafe\", layer=\"l2\", stack_optimism_io_network=${network:doublequote}}[$__interval]))",
     "legendFormat": "Unsafe L2"
    }
   ]
  },
  {
   "title": "Recommended protocol version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_protocol_versions{stack_optimism_io_network=${network:doublequote},namespace=${node:doublequote}}",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "Engine supported protocol version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_protocol_versions{stack_optimism_io_network=${network:doublequote},namespace=${node:doublequote}}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_up{namespace=${node:doublequote},stack_optimism_io_network=${network:doublequote}})"
    }
   ]
  },
  {
   "title": "L1 Head (a.k.a. unsafe)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l1_head\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "L1"
    }
   ]
  },
  {
   "title": "L2 Unsafe L1 Origin",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_unsafe\", layer=\"l1_origin\", stack_optimism_io_network=${network:doublequote}})"
    }
   ]
  },
  {
   "title": "L2 Unsafe",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_unsafe\", layer=\"l2\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "L2 Unsafe"
    }
   ]
  },
  {
   "title": "L2 Sync Speed (blocks/sec, 10m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max(rate(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_safe\", layer=\"l2\", stack_optimism_io_network=${network:doublequote}}[10m]))",
     "legendFormat": "Safe L2"
    },
    {
     "expr": "max(rate(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_unsafe\", layer=\"l2\", stack_optimism_io_network=${network:doublequote}}[10m]))",
     "legendFormat": "Unsafe L2"
    }
   ]
  },
  {
   "title": "Derivation Idle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_derivation_idle{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}})"
    }
   ]
  },
  {
   "title": "L1 Justified checkpoint (a.k.a. safe)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l1_safe\", layer=\"l1\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "L1"
    }
   ]
  },
  {
   "title": "L2 Safe L1 Origin",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_safe\", layer=\"l1_origin\", stack_optimism_io_network=${network:doublequote}})"
    }
   ]
  },
  {
   "title": "L2 Safe",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_safe\", layer=\"l2\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "L2 Safe"
    }
   ]
  },
  {
   "title": "Pipeline Resets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_pipeline_resets_total{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}})"
    }
   ]
  },
  {
   "title": "L1 Finalized checkpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l1_finalized\", layer=\"l1\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "L1"
    }
   ]
  },
  {
   "title": "L2 Finalized L1 Origin",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_finalized\", layer=\"l1_origin\", stack_optimism_io_network=${network:doublequote}})"
    }
   ]
  },
  {
   "title": "L2 Finalized",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_finalized\", layer=\"l2\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "L2 Finalized"
    }
   ]
  },
  {
   "title": "Throughput (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "max(rate(op_node_default_transactions_sequenced_total{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}}[$__interval]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Sequencing Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_sequencing_errors_total{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}})"
    }
   ]
  },
  {
   "title": "L1 derived block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l1_derived\", layer=\"l1\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "L1"
    }
   ]
  },
  {
   "title": "L1 Reorg Depth",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_l1_reorg_depth_bucket{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Sync progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l1_head\", layer=\"l1\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "L1 Head"
    },
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=~\"l2_unsafe\", layer=\"l2\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "Unsafe L2 head"
    },
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_safe\", layer=\"l2\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "Safe L2 head"
    },
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_finalized\", layer=\"l2\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "L2 Finalized"
    },
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_unsafe\", layer=\"l1_origin\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "L2 Unsafe L1 Origin"
    },
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l2_safe\", layer=\"l1_origin\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "L2 Safe L1 Origin"
    },
    {
     "expr": "max(op_node_default_refs_number{namespace=${node:doublequote}, type=\"l1_finalized\", layer=\"l1\", stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "L1 Finalized"
    }
   ]
  },
  {
   "title": "Derivation Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_derivation_errors_total{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}})"
    }
   ]
  },
  {
   "title": "L1 Reorg depth over time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_l1_reorg_depth_bucket{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publishing Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_sequencing_errors_total{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}})"
    }
   ]
  },
  {
   "title": "RPC methods requests / second (moving avg.)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(op_node_default_rpc_client_requests_total{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Engine API - forkchoiceUpdated time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_rpc_client_request_duration_seconds_bucket{namespace=${node:doublequote},method=~\"engine_forkchoiceUpdatedV[0-9]\", stack_optimism_io_network=${network:doublequote}}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "L1 RPC cache adds (+) gets (-) / min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum by (type) (rate(op_node_default_l1_source_cache_add{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}}[$__interval])) * 60",
     "legendFormat": "{{type}} add"
    },
    {
     "expr": "sum by (type) (-rate(op_node_default_l1_source_cache_get{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}}[$__interval]) * 60)",
     "legendFormat": "{{type}} get"
    }
   ]
  },
  {
   "title": "Engine API - getPayload time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_rpc_client_request_duration_seconds_bucket{namespace=${node:doublequote},method=~\"engine_getPayloadV[0-9]\", stack_optimism_io_network=${network:doublequote}}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "L2 RPC cache adds (+) gets (-) / min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum by (type) (rate(op_node_default_l2_source_cache_add{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}}[$__interval])) * 60",
     "legendFormat": "{{type}} add"
    },
    {
     "expr": "sum by (type) (-rate(op_node_default_l2_source_cache_get{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}}[$__interval]) * 60)",
     "legendFormat": "{{type}} get"
    }
   ]
  },
  {
   "title": "Engine API - newPayload time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_rpc_client_request_duration_seconds_bucket{namespace=${node:doublequote},method=~\"engine_newPayloadV[0-9]\", stack_optimism_io_network=${network:doublequote}}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Sequencer Block sealing time (less is better)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_sequencer_sealing_seconds_bucket{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Peers and streams",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "max(op_node_default_p2p_peer_count{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "peers"
    },
    {
     "expr": "max(op_node_default_p2p_stream_count{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "libp2p streams"
    }
   ]
  },
  {
   "title": "Sequencer Block building time diff (50ms sealing expected)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_sequencer_building_diff_seconds_bucket{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "L2 unsafe payloads queue size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "max(op_node_default_unsafe_payloads_buffer_len{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "Unprocessed buffered L2 unsafe blocks"
    }
   ]
  },
  {
   "title": "p2p bandwidth usage rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(rate(op_node_default_p2p_bandwidth_bytes_total{namespace=${node:doublequote},direction=\"in\", stack_optimism_io_network=${network:doublequote}}[$__interval]))",
     "legendFormat": "inbound"
    },
    {
     "expr": "max(rate(op_node_default_p2p_bandwidth_bytes_total{namespace=${node:doublequote},direction=\"out\", stack_optimism_io_network=${network:doublequote}}[$__interval]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "L2 unsafe payloads queue memory size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(op_node_default_unsafe_payloads_buffer_mem_size{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "Unprocessed buffered L2 unsafe blocks"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (job) (process_resident_memory_bytes{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "{{job}} Resident"
    },
    {
     "expr": "max by (job) (process_virtual_memory_bytes{namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}})",
     "legendFormat": "{{job}} Virtual"
    }
   ]
  },
  {
   "title": "Peer Scores [Buckets]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "rate(op_node_default_peer_scores_bucket{type=\"total\",namespace=${node:doublequote}, stack_optimism_io_network=${network:doublequote}}[10m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gossip events rate / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sum by (type) (rate(op_node_default_p2p_gossip_events_total{namespace=${node:doublequote}}[$__interval])) * 60",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}