{
 "title": "Bedrock Batcher",
 "tags": [ "public" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(op_node_default_up, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(op_batcher_default_info{cluster=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Channels",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(op_batcher_default_channel_num_frames{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "num_frames"
    },
    {
     "expr": "sum(op_batcher_default_input_bytes{cluster=\"$cluster\", stage=\"added\", namespace=\"$namespace\"})",
     "legendFormat": "input_bytes (added)"
    },
    {
     "expr": "sum(op_batcher_default_input_bytes{cluster=\"$cluster\", stage=\"closed\", namespace=\"$namespace\"})",
     "legendFormat": "input_bytes (closed)"
    },
    {
     "expr": "sum(op_batcher_default_output_bytes{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "output_bytes"
    },
    {
     "expr": "sum(op_batcher_default_output_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}) / ignoring(stage) sum(op_batcher_default_input_bytes{cluster=\"$cluster\", namespace=\"$namespace\", stage=\"closed\"})",
     "legendFormat": "compr_ratio"
    }
   ]
  },
  {
   "title": "Pending L2 Blocks - by stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max by(stage) (op_batcher_default_pending_blocks_count{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Pending L2 Block Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "op_batcher_default_pending_blocks_bytes_current{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "pending_block_bytes"
    }
   ]
  },
  {
   "title": "Avg. Channel Duration [min] [30m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "1 / (sum by(cluster, namespace, stage) (rate(op_batcher_default_channel_total{cluster=\"$cluster\", namespace=\"$namespace\"}[30m])) * 60)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "min by(layer, type) (op_batcher_default_refs_number{cluster=\"$cluster\", namespace=\"$namespace\"}) > 0",
     "legendFormat": "{{layer}}-{{type}}"
    }
   ]
  },
  {
   "title": "Block Height - Diff",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "(sum(op_batcher_default_refs_number{cluster=\"$cluster\", namespace=\"$namespace\", layer=\"l1\", type=\"latest\"}) > 0) - (sum(op_batcher_default_refs_number{cluster=\"$cluster\", namespace=\"$namespace\", layer=\"l1_origin\", type=\"loaded\"}) > 0)",
     "legendFormat": "tip - l1_origin-loaded"
    },
    {
     "expr": "(sum(op_batcher_default_refs_number{cluster=\"$cluster\", namespace=\"$namespace\", layer=\"l1\", type=\"latest\"}) > 0) - (sum(op_batcher_default_refs_number{cluster=\"$cluster\", namespace=\"$namespace\", layer=\"l1_origin\", type=\"added\"}) > 0)",
     "legendFormat": "tip - l1_origin-added"
    },
    {
     "expr": "(sum(op_batcher_default_refs_number{cluster=\"$cluster\", namespace=\"$namespace\", layer=\"l2\", type=\"loaded\"}) > 0) - (sum(op_batcher_default_refs_number{cluster=\"$cluster\", namespace=\"$namespace\", layer=\"l2\", type=\"added\"}) > 0)",
     "legendFormat": "l2-(loaded - added)"
    }
   ]
  },
  {
   "title": "Data Rates (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(op_batcher_default_output_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[20m]))",
     "legendFormat": "output_bytes[20m]"
    },
    {
     "expr": "sum(rate(op_batcher_default_pending_blocks_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[20m]))",
     "legendFormat": "pending_blocks_bytes[20m]"
    }
   ]
  },
  {
   "title": "Blob Used Bytes Histogram Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(op_batcher_default_blob_used_bytes_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[1h])))",
     "legendFormat": "95_pct_blob_bytes"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(op_batcher_default_blob_used_bytes_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[1h])))",
     "legendFormat": "50_pct_blob_bytes"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(op_batcher_default_blob_used_bytes_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[1h])))",
     "legendFormat": "75_pct_blob_bytes"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(op_batcher_default_blob_used_bytes_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[1h])))",
     "legendFormat": "25_pct_blob_bytes"
    }
   ]
  },
  {
   "title": "Blob Used Bytes Histogram",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_batcher_default_blob_used_bytes_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Compression Ratio Histogram Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(op_batcher_default_channel_compr_ratio_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[1h])))",
     "legendFormat": "95_pct_compr_ratio"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(op_batcher_default_channel_compr_ratio_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[1h])))",
     "legendFormat": "50_pct_compr_ratio"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(op_batcher_default_channel_compr_ratio_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[1h])))",
     "legendFormat": "75_pct_compr_ratio"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(op_batcher_default_channel_compr_ratio_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[1h])))",
     "legendFormat": "25_pct_compr_ratio"
    }
   ]
  },
  {
   "title": "Channel Compression Ratios",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_batcher_default_channel_compr_ratio_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Batcher Nonce",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(cluster, namespace) (op_batcher_default_txmgr_current_nonce{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "nonce"
    }
   ]
  },
  {
   "title": "Batcher Nonce",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 44 },
   "targets": [
    {
     "expr": "max by(cluster, namespace) (op_batcher_default_txmgr_current_nonce{cluster=\"$cluster\", namespace=\"$namespace\"}) != 0",
     "legendFormat": "nonce"
    }
   ]
  },
  {
   "title": "Basefee & suggested tip cap [log(wei)]",
   "type": "timeseries",
   "description": "If blob base fee is > 16x base fee, consider switching from blobs to calldata (this will be automatic if the batcher is configured for auto DA selection). Note that the batcher's internal DA switching logic uses a more involved calculation than the dashboard so may not switch DA type precisely when the panel would indicate it should -- see batcher logs filtered for cost_ratio.",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "si:wei" } },
   "targets": [
    {
     "expr": "max(op_batcher_default_txmgr_basefee_wei{cluster=\"$cluster\", namespace=\"$namespace\"} != 0)",
     "legendFormat": "basefee_wei"
    },
    {
     "expr": "max(op_batcher_default_txmgr_tipcap_wei{cluster=\"$cluster\", namespace=\"$namespace\"} != 0)",
     "legendFormat": "tipcap_wei"
    },
    {
     "expr": "max(op_batcher_default_txmgr_blob_basefee_wei{cluster=\"$cluster\", namespace=\"$namespace\"} != 0)",
     "legendFormat": "blob_basefee_wei"
    },
    {
     "expr": "op_batcher_default_txmgr_tx_type{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "da_type"
    }
   ]
  },
  {
   "title": "Publishing errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 44 },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_tx_publish_error_count{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "publish_err_{{error}}_count"
    }
   ]
  },
  {
   "title": "Requeuing events",
   "type": "logs",
   "description": "These events fire when, as a channel is about to be submitted, the batcher detects that it would be cheaper to send using a different DA layer (calldata or blobs). The blocks in the channel are requeued and a new channel is built on the fly.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\"} |= `requeing` | logfmt | label_format level=detected_level"
    }
   ]
  },
  {
   "title": "Times",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_last_publish_unix{cluster=\"$cluster\", namespace=\"$namespace\"} * 1000",
     "legendFormat": "Publish Time"
    },
    {
     "expr": "op_batcher_default_txmgr_last_confirm_unix{cluster=\"$cluster\", namespace=\"$namespace\"}*1000",
     "legendFormat": "Confirm Time"
    }
   ]
  },
  {
   "title": "Balance (ETH)",
   "type": "stat",
   "description": "Current account balance in ETH",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(op_batcher_default_balance{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 60 },
   "targets": [
    {
     "expr": "max(op_batcher_default_balance{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "RPC Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 60 },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_rpc_error_count{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "rpc_error_count"
    },
    {
     "expr": "rate(op_batcher_default_txmgr_rpc_error_count{cluster=\"$cluster\", namespace=\"$namespace\"}[10m])",
     "legendFormat": "rpc_error_rate"
    }
   ]
  },
  {
   "title": "Pending TXs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "max(op_batcher_default_txmgr_pending_txs{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "pending_txs"
    }
   ]
  },
  {
   "title": "Required TX gas bumps to inclusion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_tx_gas_bump{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "gas_bumps"
    }
   ]
  }
 ]
}