{
 "title": "Kona Sync",
 "description": "A trusted-sync instance running against mainnet and sepolia for Stage 1.4.",
 "tags": [ "public" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values({namespace=~\"kona-trusted-sync-mainnet|kona-trusted-sync-sepolia\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Derived Payloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trusted_sync_derived_attributes_count{namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Invalid Payloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trusted_sync_failed_payload_derivation{namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "FF Block",
   "type": "stat",
   "description": "Last block where derivation stalled and the cursor had to be \"fast forwarded\" to tip.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trusted_sync_fast_forward_block{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest FF",
   "type": "stat",
   "description": "Latest timestamp at which a fast-forward occurred (derivation stalled and the cursor was \"fast forwarded\" to tip)",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - trusted_sync_fast_forward_timestamp{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Stats",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "trusted_sync_safe_l2_head{namespace=\"$namespace\"}",
     "legendFormat": "Derived L2 Safe Head"
    },
    {
     "expr": "trusted_sync_reference_l2_head{namespace=\"$namespace\"}",
     "legendFormat": "Reference L2 Safe Head"
    },
    {
     "expr": "kona_derive_origin_gauge{namespace=\"$namespace\"}",
     "legendFormat": "L1 Origin"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trusted_sync_chain_id{namespace=\"$namespace\"}",
     "legendFormat": "L2 Chain ID"
    },
    {
     "expr": "trusted_sync_consensus_chain_id{namespace=\"$namespace\"}",
     "legendFormat": "L1 Chain ID"
    }
   ]
  },
  {
   "title": "Head Drift",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trusted_sync_reference_l2_head{namespace=\"$namespace\"} - trusted_sync_safe_l2_head{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Lag",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(time() - trusted_sync_latest_ref_safe_head_update{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Walkback",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trusted_sync_drift_walkback{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Walkback",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - trusted_sync_drift_walkback_timestamp{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Step Results",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trusted_sync_pipeline_steps{status=\"success\", namespace=\"$namespace\"}",
     "legendFormat": "Successful Steps"
    },
    {
     "expr": "trusted_sync_pipeline_steps{status=\"failure\", namespace=\"$namespace\"}",
     "legendFormat": "Failed Steps"
    },
    {
     "expr": "trusted_sync_pipeline_steps{status=\"origin_advance\", namespace=\"$namespace\"}",
     "legendFormat": "Origin Advances"
    },
    {
     "expr": "trusted_sync_pipeline_steps{status=\"origin_advance_failure\", namespace=\"$namespace\"}",
     "legendFormat": "Failed Advances"
    }
   ]
  },
  {
   "title": "Sync Heads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trusted_sync_safe_l2_head{namespace=\"$namespace\"}",
     "legendFormat": "Derived L2 Safe Head"
    },
    {
     "expr": "trusted_sync_reference_l2_head{namespace=\"$namespace\"}",
     "legendFormat": "Reference L2 Safe Head"
    },
    {
     "expr": "kona_derive_origin_gauge{namespace=\"$namespace\"}",
     "legendFormat": "L1 Origin"
    },
    {
     "expr": "trusted_sync_start_l2_block{namespace=\"$namespace\"}",
     "legendFormat": "Starting L2 Block"
    }
   ]
  },
  {
   "title": "Derived Payload Attributes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(trusted_sync_derived_attributes_count{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "Derived Attributes Rate"
    },
    {
     "expr": "trusted_sync_derived_attributes_count{namespace=\"$namespace\"}",
     "legendFormat": "Cumulative Derived Attributes"
    }
   ]
  },
  {
   "title": "Pipeline Step Count [Cumulative]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "trusted_sync_pipeline_steps{status=\"success\", namespace=\"$namespace\"}",
     "legendFormat": "Successful Steps"
    },
    {
     "expr": "trusted_sync_pipeline_steps{status=\"failure\", namespace=\"$namespace\"}",
     "legendFormat": "Failed Steps"
    }
   ]
  },
  {
   "title": "Batch Compression Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kona_derive_batch_compression_ratio{namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Pipeline Step Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(trusted_sync_pipeline_steps{status=\"success\", namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "Successful Step Rate"
    },
    {
     "expr": "rate(trusted_sync_pipeline_steps{status=\"failure\", namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "Failed Step Rate"
    }
   ]
  },
  {
   "title": "Origin Advances Rates (per min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "rate(trusted_sync_pipeline_steps{status=\"origin_advance\", namespace=\"$namespace\"}[15m])",
     "legendFormat": "Origin Advance Rate"
    },
    {
     "expr": "rate(trusted_sync_pipeline_steps{status=\"origin_advance_failure\", namespace=\"$namespace\"}[15m])",
     "legendFormat": "Failed Origin Advance Rate"
    }
   ]
  },
  {
   "title": "Derived Frames (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "rate(kona_derive_derived_frames_count{namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Stage Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(kona_derive_stage_advance_response_time_seconds_sum{namespace=\"$namespace\"}[15m])",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Provider Calls / Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "sum by(provider) (rate(kona_derive_provider_calls{namespace=\"$namespace\"}[15m]))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Method Calls / Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "sum by(method) (rate(kona_derive_provider_calls{namespace=\"$namespace\"}[15m]))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Stage Resets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "kona_derive_stage_resets{namespace=\"$namespace\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Providers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "L2 Chain Provider Calls / Sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 143 },
     "targets": [
      {
       "expr": "rate(kona_derive_provider_calls{provider=\"l2_chain_provider\", namespace=\"$namespace\"}[15m])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Blob Provider Calls / Min",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 143 },
     "targets": [
      {
       "expr": "rate(kona_derive_provider_calls{provider=\"blob_provider\", namespace=\"$namespace\"}[15m]) * 60",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "Beacon Client Calls / Min",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 189 },
     "targets": [
      {
       "expr": "rate(kona_derive_provider_calls{provider=\"beacon_client\", namespace=\"$namespace\"}[15m]) * 60",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Chain Provider Calls / Min",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 189 },
     "targets": [
      {
       "expr": "rate(kona_derive_provider_calls{provider=\"chain_provider\", namespace=\"$namespace\"}[15m])",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Channels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Channel Frame Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
     "targets": [
      {
       "expr": "kona_derive_current_channel_frames{namespace=\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Channel Frame Counts",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
     "targets": [
      {
       "expr": "kona_derive_channel_frame_count_bucket{namespace=\"$namespace\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attributes Queue Stage Response Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
     "targets": [
      {
       "expr": "rate(kona_derive_stage_advance_response_time_seconds_bucket{namespace=\"$namespace\", stage=\"attributes_queue\"}[10m])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Batch Queue Stage Response Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
     "targets": [
      {
       "expr": "rate(kona_derive_stage_advance_response_time_seconds_bucket{namespace=\"$namespace\", stage=\"batch_queue\"}[10m])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Channel Bank Stage Response Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
     "targets": [
      {
       "expr": "rate(kona_derive_stage_advance_response_time_seconds_bucket{namespace=\"$namespace\", stage=\"channel_bank\"}[10m])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Channel Reader Stage Response Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
     "targets": [
      {
       "expr": "rate(kona_derive_stage_advance_response_time_seconds_bucket{namespace=\"$namespace\", stage=\"channel_reader\"}[10m])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "<reserved-section>", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "<reserved-section>",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Rates by Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 240 },
     "targets": [
      {
       "expr": "sum by(job) (rate({job=\"kona-trusted-sync/kona-trusted-sync\"} |= `ERROR` [10m]))",
       "legendFormat": "Errors"
      },
      {
       "expr": "sum by(job) (rate({job=\"kona-trusted-sync/kona-trusted-sync\"} |= `WARN` [10m]))",
       "legendFormat": "Warns"
      },
      {
       "expr": "sum by(job) (rate({job=\"kona-trusted-sync/kona-trusted-sync\"} |= `INFO` [10m]))",
       "legendFormat": "Infos"
      },
      {
       "expr": "sum by(job) (rate({job=\"kona-trusted-sync/kona-trusted-sync\"} |= `DEBUG` [10m]))",
       "legendFormat": "Debugs"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |= `ERROR`"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |= `WARN`"
    }
   ]
  },
  {
   "title": "Info Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |= `INFO`"
    }
   ]
  },
  {
   "title": "Debug Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |= `DEBUG`"
    }
   ]
  },
  { "title": "Trace Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}