{
 "title": "op-conductor Health Monitor",
 "tags": [ "public" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(op_conductor_mon_leader_count,app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Core metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Leader count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "op_conductor_mon_leader_count{app_kubernetes_io_instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "increase(op_conductor_mon_errors_total{app_kubernetes_io_instance=~\"$instance\"}[5m])",
     "legendFormat": "{{node}} {{error}}"
    }
   ]
  },
  { "title": "Per node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Leader",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sum by(node, state) (op_conductor_mon_node_state{state=\"leader\", app_kubernetes_io_instance=~\"$instance\"})",
     "legendFormat": "{{node}} {{state}}"
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sum by(node, state) (op_conductor_mon_node_state{state=\"healthy\", app_kubernetes_io_instance=~\"$instance\"})",
     "legendFormat": "{{node}} {{state}}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sum by(node, state) (op_conductor_mon_node_state{state=\"active\", app_kubernetes_io_instance=~\"$instance\"})",
     "legendFormat": "{{node}} {{state}}"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sum by(node, state) (op_conductor_mon_node_state{state=\"paused\", app_kubernetes_io_instance=~\"$instance\"})",
     "legendFormat": "{{node}} {{state}}"
    }
   ]
  },
  {
   "title": "Stopped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sum by(node, state) (op_conductor_mon_node_state{state=\"stopped\", app_kubernetes_io_instance=~\"$instance\"})",
     "legendFormat": "{{node}} {{state}}"
    }
   ]
  },
  {
   "title": "Leader according to each node",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "sum by(node, leader) (op_conductor_mon_node_leader{app_kubernetes_io_instance=~\"$instance\"}) > 0",
     "legendFormat": "{{node}}: [{{leader}}]"
    }
   ]
  },
  {
   "title": "Raft cluster membership count according to each node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "op_conductor_mon_cluster_membership_count{app_kubernetes_io_instance=~\"$instance\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Raft cluster voters count according to each node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "op_conductor_mon_cluster_voters_count{app_kubernetes_io_instance=~\"$instance\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "RPC Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(node, method) (op_conductor_mon_rpc_latency{app_kubernetes_io_instance=~\"$instance\"})",
     "legendFormat": " {{node}} {{method}}"
    }
   ]
  }
 ]
}