{
 "title": "Conductor",
 "tags": [ "public" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "network",
    "query": {
     "query": "label_values(op_conductor_up,stack_optimism_io_network)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(op_conductor_up{stack_optimism_io_network=\"$network\"},app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Healthcheck Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(app_kubernetes_io_instance) (changes(op_conductor_healthchecks_count{stack_optimism_io_network=\"$network\", app_kubernetes_io_instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{app_kubernetes_io_instance}} - total"
    },
    {
     "expr": "sum by(app_kubernetes_io_instance) (changes(op_conductor_healthchecks_count{success=\"false\", stack_optimism_io_network=\"$network\", app_kubernetes_io_instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{app_kubernetes_io_instance}} - error"
    }
   ]
  },
  {
   "title": "Sequencer Starts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(app_kubernetes_io_instance) (changes(op_conductor_sequencer_starts_count{success=\"true\", stack_optimism_io_network=\"$network\", app_kubernetes_io_instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{app_kubernetes_io_instance}} success"
    },
    {
     "expr": "sum by(app_kubernetes_io_instance) (changes(op_conductor_sequencer_starts_count{success=\"false\", stack_optimism_io_network=\"$network\", app_kubernetes_io_instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{app_kubernetes_io_instance}} failed"
    }
   ]
  },
  {
   "title": "Leadership Transfers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(app_kubernetes_io_instance) (changes(op_conductor_leader_transfers_count{success=\"true\", stack_optimism_io_network=\"$network\", app_kubernetes_io_instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{app_kubernetes_io_instance}} success"
    },
    {
     "expr": "sum by(app_kubernetes_io_instance) (changes(op_conductor_leader_transfers_count{success=\"false\", stack_optimism_io_network=\"$network\", app_kubernetes_io_instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{app_kubernetes_io_instance}} failed"
    }
   ]
  },
  {
   "title": "Sequencer Stops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(app_kubernetes_io_instance) (changes(op_conductor_sequencer_stops_count{success=\"true\", stack_optimism_io_network=\"$network\", app_kubernetes_io_instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{app_kubernetes_io_instance}} success"
    },
    {
     "expr": "sum by(app_kubernetes_io_instance) (changes(op_conductor_sequencer_stops_count{success=\"false\", stack_optimism_io_network=\"$network\", app_kubernetes_io_instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{app_kubernetes_io_instance}} failed"
    }
   ]
  },
  {
   "title": "State Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(app_kubernetes_io_instance) (changes(op_conductor_state_changes_count{stack_optimism_io_network=\"$network\", app_kubernetes_io_instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Loop Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, app_kubernetes_io_instance) (rate(op_conductor_loop_execution_time_bucket{stack_optimism_io_network=~\"$network\", app_kubernetes_io_instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{app_kubernetes_io_instance}} - p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, app_kubernetes_io_instance) (rate(op_conductor_loop_execution_time_bucket{stack_optimism_io_network=~\"$network\", app_kubernetes_io_instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{app_kubernetes_io_instance}} - p50"
    }
   ]
  }
 ]
}